# Generated by Django 4.1.7 on 2023-05-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_courses_cimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='cimg',
            new_name='image',
        ),
    ]
