# Generated by Django 4.1.7 on 2023-05-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_cimg_courses_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='image',
            new_name='images',
        ),
    ]
