# Generated by Django 4.1.7 on 2023-05-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_image_courses_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='images',
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
