# Generated by Django 4.1.7 on 2023-05-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_courses_images_courses_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='image',
            new_name='image1',
        ),
    ]
