# Generated by Django 4.1.7 on 2023-05-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_image1_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='ctrainer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
