# Generated by Django 4.1.7 on 2023-05-20 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_courses_ctrainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nstdName', models.CharField(max_length=20)),
                ('nmail', models.EmailField(max_length=254)),
                ('nmobile', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('graduation', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses')),
            ],
        ),
    ]
