# Generated by Django 4.1.7 on 2023-06-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='c_deatils',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='ckey',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
