# Generated by Django 4.1.7 on 2023-06-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_courses_c_deatils_courses_ckey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='c_deatils',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='ckey',
            field=models.TextField(null=True),
        ),
    ]
