# Generated by Django 4.1.7 on 2023-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='course',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
