# Generated by Django 4.1.7 on 2023-06-22 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_test_interview_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='marks',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
