# Generated by Django 4.1.7 on 2023-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_test_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
