# Generated by Django 4.1.7 on 2023-06-26 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_interview_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
