# Generated by Django 4.1.7 on 2023-06-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_demo_created_newstudent_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='newstudent',
            name='created',
        ),
        migrations.RemoveField(
            model_name='removedstudent',
            name='course',
        ),
    ]
