# Generated by Django 4.1.7 on 2023-06-29 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_demo_created_at_newstudent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='performance',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
