# Generated by Django 4.1.7 on 2023-07-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_interview_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
