# Generated by Django 4.1.7 on 2023-07-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_interview_marks_alter_interview_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='performance',
        ),
    ]
