# Generated by Django 4.1.7 on 2023-07-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_interview_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passouts',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.courses'),
        ),
    ]
