# Generated by Django 4.1.7 on 2023-07-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_interview_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='removedstudent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.courses'),
        ),
    ]
