# Generated by Django 4.1.7 on 2023-08-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_admissionform'),
    ]

    operations = [
        migrations.CreateModel(
            name='jopForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_city', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('degree_college', models.CharField(max_length=255)),
                ('passed_out_year', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('post_graduation', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_degree_college', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_passed_out_year', models.IntegerField(blank=True, null=True)),
                ('relevant_experience', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_person_contact', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
