# Generated by Django 4.1.7 on 2023-08-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_jopform'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
