# Generated by Django 4.2.2 on 2023-08-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_student_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
